name: Auto-Fly
version: '${project.version}'
main: win.trystage.autofly.AutoFly
author: BrainRTP Trystage
commands:
  fly:
    description: Toggle player flight
    usage: /fly
    permission: group.vip
    permission-message: Unknown command. Type "/help" for help.